In [197]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
from tqdm import tqdm
pd.set_option('display.max_rows', 1000)
import re
import numpy as np
from datetime import datetime

In [198]:
bnb = pd.read_csv('data/airbnb_v1.csv', low_memory=False)
bnb

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,NaN,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,NaN,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,NaN,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,90

In [199]:
bnb.columns = bnb.loc[0]
bnb = bnb.iloc[1:]
bnb

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,NaN,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,NaN,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,NaN,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,NaN,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,90

In [200]:
bnb.columns

Index([                       'id',                      'name',
                       'host   id',               '[host_name]',
             'neighbourhood group',             'neighbourhood',
                        'latitude',                 'longitude',
                   'room and type',            'minimum nights',
       'number of reviews (total)',        'last review (date)',
               'reviews per month',                     'floor',
                       'noise.dB.',                         nan,
                           'price'],
      dtype='object', name=0)

In [201]:
bnb = bnb[[                       'id',                      'name',
                       'host   id',               '[host_name]',
             'neighbourhood group',             'neighbourhood',
                        'latitude',                 'longitude',
                   'room and type',            'minimum nights',
       'number of reviews (total)',        'last review (date)',
               'reviews per month',                     'floor',
                       'noise.dB.',                         
                           'price']]
bnb

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,90

In [202]:
bnb[bnb['name'].isna()]

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
366,154934,NaN,745069,Kimberly,Manhattan,Harlem,40.82426,-73.9463,Private room,3,38,2018-05-08,0.42,First Floor,56.0542782840785dB,$75approx
373,160994,NaN,770831,James,Manhattan,East Village,40.72972,-73.97995,Entire home/apt,2,103,2019-06-24,1.08,First Floor,56.0542782840785dB,$200
436,193853,NaN,48599,Anastasia,Manhattan,Chelsea,40.74033,-74.00024,Entire home/apt,6,23,2018-05-21,0.27,First Floor,56.0542782840785dB,149
476,219793,NaN,1138692,Keera (Jena),Manhattan,Lower East Side,40.71813,-73.98416,Entire home/apt,1,29,2015-06-03,0.31,First Floor,56.0542782840785dB,199
498,228496,NaN,1192424,Gordon,Manhattan,West Village,40.73507,-74.00048,Entire home/apt,3,13,2019-05-26,0.15,First Floor,56.0542782840785dB,225
592,263232,NaN,1381171,Nicole,Manhattan,Harlem,40.82151,-73.94516,Entire home/apt,1,1,2019-01-27,0.18,First Floor,56.0542782840785dB,$155
778,371138,NaN,1869567,Max,Brooklyn,Greenpoint,40.72488,-73.94013,Entire home/apt,2,5,2015-10-12,0.1,First Floor,69.0564645654522dB,190
824,411918,NaN,2050338,Verena,Brooklyn,Crown Heights,40.66924,-73.94406,Entire home/apt,5,125,2019-07-02,1.47,First Floor,69.05646457,$160
1098,593320,NaN,2929756,Chris,Manhattan,Inwood,40.86345,-73.92039,Private room,4,160,2019-06-12,1.89,First Floor,56.05427828,55
1150,639199,NaN,1483081,Marina,Staten Island,Tottenville,40.50868,-74.23986,Entire home/apt,3,59,2019-07-08,0.82,First Floor,50.9643603379373dB,299
1229,695216,NaN,3558158,Natalie,Brooklyn,Fort Greene,40.69096,-73.97241° W,Entire home/apt,2,119,2018-01-25,1.46,First Floor,69.0564645654522dB,134
1281,728493,NaN,1601416,Clement & Natalia,Manhattan,Harlem,40.81073,-73.9437,Private room,7,67,2019-01-01,0.87,First Floor,56.0542782840785dB,70
1315,749108,NaN,3936154,Molly,Brooklyn - **Borough**,Clinton Hill,40.68391,-73.96201,Entire home/apt,3,12,2019-07-01,0.15,1,70.0564645654522dB,$575
1355,769279,NaN,1228080,Sasha,Manhattan,East Village,40.72439N,-73.97767,Private room,7,1,2016-05-01,0.03,First Floor,56.0542782840785dB,100
1356,770514,NaN,4064804,Niki,Manhattan,Flatiron District,40.73997,-73.98789,Entire home/apt,1,1,2014-09-22,0.02,First Floor,56.05427828,195
1423,799945,NaN,149929,Obed,Brooklyn,Fort Greene,40.68537,-73.97713,Private room,8,32,2019-06-29,0.4,1,69.0564645654522dB,40
1608,887292,NaN,4704914,Robert,Brooklyn,Bushwick,40.69982N,-73.91957° W,Entire home/apt,3,106,2019-05-08,1.42,First Floor,69.0564645654522dB,139
1684,958444,NaN,5214644,Noelva,Bronx,City Island,40.85235,-73.78873,Entire home/apt,3,67,2018-06-10,0.91,Fifth Floor,78.4740737858228dB,84
1764,1029482,NaN,5664550,Kelly,Manhattan,East Village,40.72346,-73.97907,Private room,5,35,2019-06-10,0.46,First Floor,56.0542782840785dB,95
2055,1335510,NaN,4202236,John,Brooklyn,Williamsburg,40.71657,-73.9597,Entire home/apt,7,3,2013-11-21,0.04,First Floor,69.05646457,115
2289,1615764,NaN,6676776,Peter,Manhattan,Battery Park City,40.71239,-74.0162,Entire home/apt,1000,0,NaN,NaN,First Floor,57.0542782840785dB,400
2317,1652236,NaN,3562322,Lord Daniel,Brooklyn,Bedford-Stuyvesant,40.68708,-73.95126,Private room,6,41,2019-07-03,0.58,First Floor,69.0564645654522dB,31
2336,1672977,NaN,2119276,Host,Manhattan,Hell's Kitchen,40.76703N,-73.98874,Entire home/apt,30,17,2019-04-12,0.35,First Floor,56.0542782840785dB,$195
2389,1732498,NaN,1818792,Clarissa & Rich,Brooklyn,Greenpoint,40.72716,-73.94971,Entire home/apt,2,25,2016-10-18,0.44,First Floor,69.0564645654522dB,199
2449,1801036,NaN,8200820,Valerie,Brooklyn,Williamsburg,40.7187,-73.95133,Private room,2,14,2014-02-01,0.2,First Floor,69.0564645654522dB,45
2570,1908986,NaN,9906590,Evan,Manhattan,Upper East Side,40.77785,-73.9454° W,Entire home/apt,1,0,NaN,NaN,First Floor,57.0542782840785dB,350
2673,1987371,NaN,1525582,Christina,Brooklyn,Williamsburg,40.71971N,-73.95998° W,Private room,3,176,2019-06-21,2.63,First Floor,69.0564645654522dB,79
2746,2055050,NaN,10525320,Candace,Manhattan,Upper East Side,40.77376,-73.95343,Entire home/apt,5,54,2019-06-01,0.9,First Floor,56.0542782840785dB,125
2847,2115773,NaN,514261,Vanessa,Brooklyn,South Slope,40.66639,-73.98706,Private room,7,0,NaN,NaN,First Floor,69.0564645654522dB,$120
2898,2159193,NaN,11012377,Edward,Brooklyn,Carroll Gardens,40.68497,-73.9902,Entire home/apt,5,2,2019-04-19,0.32,First Floor,69.0564645654522dB,125
2974,2237063,NaN,11313778,Jian,Manhattan,Kips Bay,40.74163,-73.97533,Entire home/apt,7,22,2019-06-29,0.46,First Floor,56.0542782840785dB,105
3174,2465699,NaN,12608261,Jimmie,Manhattan,Harlem,40.79841,-73.95257° W,Private room,2,27,2019-04-12,0.44,First Floor,56.0542782840785dB,72
3196,2488227,NaN,12732385,Asaf,Manhattan,Lower East Side,40.72005,-73.98609,Entire home/apt,6,55,2019-06-15,0.85,First Floor,56.0542782840785dB,$180
3344,2702489,NaN,13830544,Renee,Brooklyn,Bushwick,40.69574,-73.93111,Entire home/apt,5,32,2019-06-16,0.66,First Floor,69.05646457,85
3368,2739884,NaN,3417714,Cong,Manhattan,Hell's Kitchen,40.75927N,-73.99223° W,Entire home/apt,5,14,2016-06-02,0.25,First Floor,56.05427828,189
3579,3070876,NaN,2448006,El Haj,Manhattan,Harlem,40.80392,-73.94685,Private room,3,5,2016-10-20,0.1,First Floor,56.0542782840785dB,75
3602,3101058,NaN,15767190,Mark,Brooklyn,Flatbush,40.65235,-73.9635,Entire home/apt,2,2,2017-06-28,0.08,First Floor,69.0564645654522dB,109
3677,3208904,NaN,16257970,Jackie,Manhattan,Lower East Side,40.71254,-73.98535,Private room,3,231,2019-07-07,3.72,First Floor,56.0542782840785dB,$89
3785,3328706,NaN,16805656,Fernando,Manhattan,Upper West Side,40.79893,-73.96249,Private room,1,146,2019-06-23,2.67,1,56.0542782840785dB,90
3819,3375448,NaN,2377104,Hannah,Brooklyn,Williamsburg,40.71122,-73.94985,Entire home/apt,2,257,2019-06-23,4.21,First Floor,69.0564645654522dB,225
3894,3468486,NaN,17475146,C,Manhattan,East Harlem,40.80409N,-73.93988,Entire home/apt,7,1,2014-07-28,0.02,First Floor,56.05427828,70
3905,3485146,NaN,6707119,Parnell,Manhattan,Harlem,40.8079,-73.94887,Entire home/apt,1,1,2014-12-30,0.02,First Floor,56.0542782840785dB,150
3916,3499016,NaN,17618198,Edvaldo,Queens,Ditmars Steinway,40.77902,-73.90768,Private room,2,2,2014-09-22,0.03,5th Floor,62.4786320745479dB,100
4094,3687172,NaN,5771331,Alex,Manhattan,Greenwich Village,40.72858,-73.99951,Entire home/apt,1,20,2016-05-04,0.33,First Floor,56.0542782840785dB,190
4135,3738529,NaN,19111611,Chaim,Brooklyn,Navy Yard,40.69817,-73.9654,Entire home/apt,1,7,2016-07-11,0.12,First Floor,69.0564645654522dB,$150
4193,3793542,NaN,700913,Gage,Brooklyn - **Borough**,Williamsburg,40.71601,-73.95359,Entire home/apt,30,12,2018-08-13,0.2,First Floor,69.0564645654522dB,185
4480,4081926,NaN,21171867,Jennifer And Basil,Queens,Springfield Gardens,40.67425,-73.75796° W,Entire home/apt,1,279,2019-06-16,5.02,Fifth Floor,62.4786320745479dB,$110
4505,4109420,NaN,19914713,Samantha,Queens,Astoria,40.76177,-73.91359,Entire home/apt,2,47,2019-07-07,0.81,5,62.47863207,110
4611,4209595,NaN,20700823,Jesse,Manhattan,Greenwich Village,40.73473,-73.99244,Entire home/apt,1,1,2015-01-01,0.02,First Floor,56.05427828,$225
4691,4282998,NaN,9471525,Chris,Manhattan,Kips Bay,40.74092,-73.97817,Entire home/apt,7,9,2019-01-05,0.16,1,56.0542782840785dB,$200approx
4772,4370230,NaN,22686810,Michaël,Manhattan,Nolita,40.72046,-73.9955,Entire home/apt,7,5,2016-01-02,0.09,First Floor,56.0542782840785dB,215/- only
4793,4393519,NaN,6032373,Vyacheslav,Manhattan,Hell's Kitchen,40.7659,-73.99543,Entire home/apt,2,2,2015-01-02,0.04,First Floor,56.05427828,200
4814,4412533,NaN,22904933,Charlene,Manhattan,East Harlem,40.79765,-73.94022,Private room,3,56,2019-05-27,1.1,First Floor,56.0542782840785dB,$79
4927,4517848,NaN,7245581,Michael,Manhattan,Washington Heights,40.83335,-73.94048,Entire home/apt,74,7,2018-08-31,0.14,First Floor,56.0542782840785dB,$67
4987,4573897,NaN,21935479,Crysdian,Manhattan,Inwood,40.86821,-73.92128,Private room,2,70,2019-06-08,1.37,First Floor,56.0542782840785dB,76
4994,4581788,NaN,21600904,Lucie,Brooklyn,Williamsburg,40.7137,-73.94378,Private room,1,0,NaN,NaN,First Floor,69.0564645654522dB,150
5017,4603012,NaN,45609,Sean,Brooklyn,Greenpoint,40.73132,-73.95831,Entire home/apt,15,22,2019-04-30,0.39,First Floor,69.0564645654522dB,149
5090,4651354,NaN,24020050,Max,Manhattan,Chinatown,40.71566,-73.99076,Entire home/apt,4,25,2019-04-15,0.48,1,56.05427828,189
5124,4678795,NaN,24048208,Maura,Brooklyn,Bedford-Stuyvesant,40.6848,-73.95728,Entire home/apt,3,0,NaN,NaN,First Floor,69.05646457,140
5239,4756856,NaN,1832442,Carolina,Brooklyn,Bushwick,40.70046,-73.92825,Private room,1,0,NaN,NaN,First Floor,69.05646457,70
5251,4762718,NaN,22814290,Maximiliano,Manhattan,Upper West Side,40.78143N,-73.98321,Entire home/apt,5,0,NaN,NaN,1,56.0542782840785dB,$250
5272,4774658,NaN,24625694,Josh,Manhattan,Washington Heights,40.85198,-73.93108° W,Private room,1,0,NaN,NaN,First Floor,56.0542782840785dB,40
5489,4909427,NaN,6230230,John,Manhattan,Lower East Side,40.71806,-73.98493,Private room,20,13,2016-01-02,0.25,First Floor,56.0542782840785dB,$110
5837,5382755,NaN,26377263,Stat,Brooklyn,East Flatbush,40.6593,-73.93512,Private room,30,1,2016-09-30,0.03,First Floor,69.0564645654522dB,44
6069,5725154,NaN,29683852,Lindsay,Brooklyn,Downtown Brooklyn,40.68927,-73.98423,Entire home/apt,1,2,2015-04-12,0.04,First Floor,69.05646457,150
6185,5881122,NaN,22087408,Dominik,Manhattan,Lower East Side,40.71735,-73.98213,Private room,1,44,2019-06-10,1.15,First Floor,56.0542782840785dB,125
6217,5919646,NaN,410962,Mike,Manhattan,Hell's Kitchen,40.76738,-73.98466,Entire home/apt,3,14,2019-07-07,0.32,First Floor,56.0542782840785dB,200
6352,6105140,NaN,946182,Zachary,Brooklyn,Bedford-Stuyvesant,40.68582,-73.94231,Private room,1,19,2019-05-26,0.7,First Floor,69.0564645654522dB,76
6606,6370889,NaN,33198779,Catherine,Manhattan,Washington Heights,40.84064,-73.93727,Private room,1,4,2015-10-31,0.08,First Floor,56.05427828,35
6642,6400482,NaN,15195194,Akiea,Manhattan,Washington Heights,40.839,-73.94543,Entire home/apt,1,4,2015-07-30,0.08,First Floor,56.0542782840785dB,115
6752,6506449,NaN,34013546,Yelena,Manhattan,Upper West Side,40.79324,-73.97489,Entire home/apt,1,2,2015-06-22,0.04,First Floor,56.05427828,140
6781,6544347,NaN,2232455,Zach,Brooklyn,Park Slope,40.67289,-73.97129,Entire home/apt,7,4,2018-08-06,0.08,1,69.0564645654522dB,150
6950,6692574,NaN,22727131,Iris,Queens,Flushing,40.75529,-73.83043,Entire home/apt,7,1,2015-11-01,0.02,Fifth Floor,62.47863207,$150
6952,6698963,NaN,12432650,Yazmany,Manhattan,Chinatown,40.7142,-73.99119,Entire home/apt,5,14,2018-12-29,0.45,First Floor,56.0542782840785dB,$250
6962,6705558,NaN,16462666,Ali,Brooklyn,Williamsburg,40.71506,-73.96182,Private room,2,1,2017-02-15,0.03,First Floor,69.0564645654522dB,103
7049,6782407,NaN,31147528,Huei-Yin,Brooklyn,Williamsburg,40.71354,-73.93882,Private room,1,0,NaN,NaN,First Floor,69.0564645654522dB,45
7098,6812924,NaN,19109608,Elle,Queens,Astoria,40.76219,-73.91963° W,Entire home/apt,1,229,2019-06-16,4.65,Fifth Floor,62.4786320745479dB,$135
7137,6854404,NaN,35919822,Christian,Manhattan,Financial District,40.70892,-74.01325,Entire home/apt,14,1,2015-09-12,0.02,First Floor,56.05427828,$130
7353,7037999,NaN,34546849,Amber,Brooklyn - **Borough**,Bedford-Stuyvesant,40.68742,-73.92825,Private room,2,34,2019-07-01,0.7,First Floor,69.05646457,50
7461,7132891,NaN,23988743,Rachid,Brooklyn,Bushwick,40.69319,-73.92375,Private room,2,22,2019-06-04,0.46,First Floor,69.0564645654522dB,$75
7493,7180015,NaN,37614545,Linda,Queens,Astoria,40.75871,-73.91112,Private room,1,0,NaN,NaN,Fifth Floor,62.4786320745479dB,$85
7543,7243708,NaN,3302103,Steph,Brooklyn,Clinton Hill,40.69158N,-73.96699,Private room,2,6,2016-11-19,0.12,First Floor,69.05646457,65
7613,7320522,NaN,38350446,Chris,Manhattan,Hell's Kitchen,40.76146,-73.9896,Private room,5,5,2016-11-28,0.13,First Floor,56.0542782840785dB,160
7637,7339802,NaN,38452274,Aly,Manhattan,Harlem,40.82196N,-73.94247,Entire home/apt,3,14,2018-01-12,0.29,First Floor,56.0542782840785dB,100
7653,7349064,NaN,5042891,Alon,Manhattan,Midtown,40.76579,-73.98057,Entire home/apt,5,0,NaN,NaN,First Floor,56.0542782840785dB,260
7982,7679697,NaN,5513694,Paul,Manhattan,Hell's Kitchen,40.76377,-73.98786,Entire home/apt,2,49,2019-05-10,1.06,First Floor,56.0542782840785dB,$200
7984,7680504,NaN,1550888,Miss Carolyn,Brooklyn,Bedford-Stuyvesant,40.68001,-73.94971,Entire home/apt,30,11,2019-05-31,0.29,First Floor,69.0564645654522dB,$150
7989,7688481,NaN,12620454,Will,Brooklyn,Bushwick,40.70442,-73.92484° W,Entire home/apt,5,27,2017-01-01,0.57,1,69.0564645654522dB,220
8092,7763203,NaN,1112560,Mary,Brooklyn,Bedford-Stuyvesant,40.6857,-73.95595,Private room,5,28,2019-06-15,0.6,First Floor,69.0564645654522dB,89
8263,7902556,NaN,3041587,Richy,Manhattan,Financial District,40.70395,-74.00995,Private room,14,121,2019-06-01,2.58,First Floor,56.05427828,98
8499,8164877,NaN,9862206,Devon,Brooklyn,Williamsburg,40.71697,-73.95919,Private room,1,19,2016-07-01,0.41,First Floor,69.05646457,70
8575,8241378,NaN,43461780,Andrew,Manhattan,West Village,40.73618,-74.00201,Private room,1,0,NaN,NaN,First Floor,56.0542782840785dB,109
8633,8294525,NaN,25266527,Maria,Brooklyn,Bensonhurst,40.62054,-73.99828,Entire home/apt,3,6,2017-01-17,0.13,First Floor,69.05646457,60
8689,8367271,NaN,2477248,Christopher,Brooklyn,Fort Greene,40.68602,-73.97386,Entire home/apt,4,4,2017-01-04,0.09,First Floor,69.0564645654522dB,150
8705,8381381,NaN,2284111,Su,Manhattan,Hell's Kitchen,40.76599,-73.98388,Entire home/apt,1,0,NaN,NaN,First Floor,56.0542782840785dB,152
8928,8615012,NaN,44620317,Claudia,Queens,Corona,40.73977,-73.85777,Shared room,1,34,2018-09-21,0.76,5th Floor,62.4786320745479dB,37
9028,8721444,NaN,45774825,Saman,Manhattan,Midtown,40.7675,-73.98228,Entire home/apt,7,15,2018-07-08,0.34,First Floor,56.0542782840785dB,175
9124,8832355,NaN,4703687,Daphne,Brooklyn,Greenpoint,40.72311,-73.93819,Entire home/apt,2,1,2016-02-27,0.02,1,69.0564645654522dB,150
9253,8964740,NaN,46851431,Anthony,Manhattan,Murray Hill,40.74637,-73.97469,Entire home/apt,1,0,NaN,NaN,First Floor,56.0542782840785dB,$104
9300,9024193,NaN,2856748,Ruchi,Manhattan,Midtown,40.75251N,-73.97262,Entire home/apt,30,0,NaN,NaN,First Floor,56.0542782840785dB,175
9357,9066389,NaN,47289872,Kara,Manhattan,Lower East Side,40.72004,-73.99026,Entire home/apt,1,2,2015-11-25,0.05,1,56.0542782840785dB,190
9362,9078632,NaN,42570179,Joanne,Manhattan,Washington Heights,40.83559,-73.94552,Private room,2,53,2018-06-29,1.18,1,56.05427828,$75
9397,9107846,NaN,6509584,Lila,Manhattan,Upper West Side,40.80059,-73.96552,Entire home/apt,1,123,2019-07-01,2.89,First Floor,56.05427828,75
9531,9247923,NaN,46631730,Anne,Manhattan,Greenwich Village,40.73297,-73.99217,Entire home/apt,2,9,2016-11-03,0.21,First Floor,56.0542782840785dB,325
9574,9295059,NaN,11797330,Casey,Manhattan,Upper East Side,40.78397,-73.95041° W,Entire home/apt,3,18,2016-07-25,0.44,First Floor,56.0542782840785dB,139
9604,9325951,NaN,33377685,Jonathan,Manhattan,Hell's Kitchen,40.76436,-73.98573,Entire home/apt,4,1,2016-01-05,0.02,First Floor,56.0542782840785dB,190
9680,9370896,NaN,46638648,Geert,Brooklyn,Bedford-Stuyvesant,40.68503,-73.93809,Entire home/apt,29,12,2018-08-20,0.31,First Floor,69.05646457,140
9761,9425357,NaN,31985378,Adrian,Brooklyn,Williamsburg,40.7158,-73.95587,Private room,2,3,2019-06-10,0.48,First Floor,69.05646457,90
9823,9464605,NaN,5776966,Lily,Manhattan,Gramercy,40.73683,-73.98191,Private room,3,21,2019-07-05,0.47,First Floor,56.0542782840785dB,61
9882,9497513,NaN,1850477,Michela,Brooklyn,Crown Heights,40.67797,-73.94675,Private room,3,0,NaN,NaN,First Floor,69.0564645654522dB,45
9889,9507521,NaN,49268145,James,Brooklyn,South Slope,40.66872,-73.98648,Entire home/apt,2,2,2016-01-01,0.05,First Floor,69.0564645654522dB,$275
10151,9696653,NaN,5291029,Qiyao,Manhattan,Greenwich Village,40.73411,-73.99787,Entire home/apt,1,111,2019-02-25,2.57,First Floor,56.0542782840785dB,108
10310,9787590,NaN,50448556,Miguel,Manhattan,Harlem,40.80316,-73.95189,Entire home/apt,5,0,NaN,NaN,First Floor,56.0542782840785dB,300
10359,9810235,NaN,50539403,Yuri,Manhattan,Tribeca,40.71819,-74.00833,Entire home/apt,4,0,NaN,NaN,First Floor,57.0542782840785dB,500
10592,9937547,NaN,30283594,Kara,Manhattan,Upper East Side,40.76453,-73.95911,Entire home/apt,30,0,NaN,NaN,First Floor,57.05427828,369
10601,9940337,NaN,14314420,Josh,Brooklyn,South Slope,40.66086,-73.98421,Entire home/apt,2,21,2019-04-21,0.82,First Floor,69.0564645654522dB,150
10674,9994304,NaN,47022650,Jillian,Manhattan,East Harlem,40.7933N,-73.93424,Entire home/apt,1,48,2019-07-01,1.26,First Floor,56.0542782840785dB,150
10793,10052289,NaN,49522403,Vanessa,Brooklyn,Brownsville,40.66409,-73.92314,Private room,3,3,2016-08-18,0.07,First Floor,69.05646457,$50
10829,10071225,NaN,40532707,Isidora,Brooklyn,Bedford-Stuyvesant,40.68729,-73.95556,Private room,1,1,2016-01-06,0.02,First Floor,69.0564645654522dB,39
11099,10383284,NaN,53411078,Caroline,Brooklyn,Bushwick,40.6863,-73.91365,Private room,1,1,2018-06-24,0.08,First Floor,69.0564645654522dB,75
11130,10433284,NaN,5487321,Xinxin,Manhattan,Gramercy,40.73562N,-73.98308,Private room,1,0,NaN,NaN,1,56.0542782840785dB,90
11233,10575811,NaN,14611780,Paige,Brooklyn,Columbia St,40.68928,-73.99903,Entire home/apt,1,5,2018-12-30,0.14,First Floor,69.0564645654522dB,105
11806,11580884,NaN,59075666,Das,Brooklyn,Williamsburg,40.70395,-73.93367,Private room,6,11,2018-09-07,0.27,First Floor,69.0564645654522dB,50
11978,11791225,NaN,23269511,Michael,Queens,AstoriaQueens-Queens,40.76792N,-73.91175,Private room,5,1,2016-05-27,0.03,Fifth Floor,62.4786320745479dB,50
12002,11829419,NaN,62915940,Baochen,Brooklyn,Borough Park,40.6311N,-74.00445,Private room,1,9,2016-08-09,0.24,First Floor,69.0564645654522dB,35
12072,11944718,NaN,13509844,Ara,Manhattan,East Harlem,40.79665,-73.94928,Private room,7,7,2016-08-14,0.18,First Floor,56.0542782840785dB,69
12167,12071454,NaN,48764969,Alina,Brooklyn,Bushwick,40.6826,-73.90411° W,Private room,6,28,2019-04-14,0.7,First Floor,69.0564645654522dB,40
12391,12344949,NaN,33993577,Nick,Manhattan,Harlem,40.80882,-73.94654,Entire home/apt,5,0,NaN,NaN,First Floor,57.0542782840785dB,350
12605,12657527,NaN,46047223,Sarah,Brooklyn,Crown Heights,40.66612N,-73.93696,Shared room,1,0,NaN,NaN,First Floor,69.0564645654522dB,20
12690,12762497,NaN,11811612,Heather,Brooklyn,Flatbush,40.65392,-73.95364,Entire home/apt,15,7,2018-09-06,0.19,First Floor,69.0564645654522dB,62
12713,12788962,NaN,390251,Lilly,Manhattan,Harlem,40.79986,-73.95387,Private room,2,5,2019-04-08,0.36,First Floor,56.05427828,105
12722,12797684,NaN,69715276,Yan,Manhattan,Upper West Side,40.79843,-73.96404,Private room,1,0,NaN,NaN,1,56.05427828,100
12739,12813206,NaN,7609268,Zoey,Brooklyn,Sunset Park,40.65038,-74.00551,Entire home/apt,3,25,2019-06-30,0.73,First Floor,69.05646457,99
12782,12855923,NaN,33906660,Trevor,Manhattan,Harlem,40.8242,-73.94777,Private room,1,154,2019-07-02,4.03,First Floor,56.0542782840785dB,65
12923,12988898,NaN,71552588,Andrea,Bronx,Fordham,40.86032,-73.88493,Shared room,1,0,NaN,NaN,Fifth Floor,78.47407379,130
12994,13052968,NaN,26959668,Flo And Erin,Brooklyn,Fort Greene,40.68748,-73.97397,Entire home/apt,3,19,2019-05-28,0.51,First Floor,69.0564645654522dB,125
13016,13065356,NaN,42399786,Braydon,Manhattan,West Village,40.73564,-73.99823,Entire home/apt,3,100,2018-09-15,2.62,First Floor,56.0542782840785dB,145
13207,13191433,NaN,49117269,Varos,Queens,Long Island City,40.75768N,-73.92897° W,Private room,15,14,2019-04-13,0.88,Fifth Floor,62.4786320745479dB,75
13323,13276525,NaN,71176668,David,Manhattan,Harlem,40.81604,-73.94017,Private room,2,20,2019-06-03,0.58,First Floor,56.0542782840785dB,110
13411,13343199,NaN,4243971,Jeanne,Brooklyn - **Borough**,Prospect-Lefferts Gardens,40.6602,-73.96017° W,Entire home/apt,2,15,2019-01-22,0.98,First Floor,69.0564645654522dB,329

In [203]:
bnb.describe()

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
count,39118,38702,39118,39102,39118,39088,39118,39118,39118,39118,39118,31140,31140,39118,39118,39118
unique,39118,38073,30935,9962,11,307,20218,17555,5,116,374,1707,907,30,95,1473
top,2539,New york Multi-unit building,219517861,Michael,Manhattan,Williamsburg,40.71813,-73.95427,Entire home/apt,1,0,2019-06-23,0.02,First Floor,56.0542782840785dB,100
freq,1,15,257,347,17329,3124,13,14,20276,10120,7978,1128,736,30053,12059,1269

In [204]:
bnb.dtypes

0
id                           object
name                         object
host   id                    object
[host_name]                  object
neighbourhood group          object
neighbourhood                object
latitude                     object
longitude                    object
room and type                object
minimum nights               object
number of reviews (total)    object
last review (date)           object
reviews per month            object
floor                        object
noise.dB.                    object
price                        object
dtype: object

In [205]:
i=0
for entry in bnb['id']:
    i += 1
    if type(entry) != int:
        if not entry.isnumeric():
            print(entry)
            print(i)

52$$$38
9

In [206]:
bnb['id'] = bnb['id'].replace('52$$$38', '5238')

In [207]:
bnb.iloc[8,0]

'5238'

In [208]:
bnb['id']=bnb['id'].astype('int')

In [209]:
bnb = bnb.rename(columns={'host   id':'host id', '[host_name]':'host name'})

In [210]:
for entry in bnb['host id']:
    if type(entry) != int:
        if not entry.isnumeric():
            print(entry)

2,,,11877

In [211]:
bnb['host id'] = bnb['host id'].replace('2,,,11877', '211877')

In [212]:
bnb['host id']=bnb['host id'].astype('int')

In [213]:
bnb['neighbourhood group'].value_counts()

Manhattan                 17329
Brooklyn                  13989
Queens                     4533
Brooklyn - **Borough**      905
Brooklyn Borough            890
Bronx                       800
brklyn                      300
Staten Island               299
broxn                        40
  bronx_borugh               30
B-r-0-n-x                     3
Name: neighbourhood group, dtype: int64

In [214]:
bnb['neighbourhood group']=bnb['neighbourhood group'].replace(('Brooklyn - **Borough**','Brooklyn Borough','brklyn'), 'Brooklyn')

In [215]:
bnb['neighbourhood group']=bnb['neighbourhood group'].replace(('broxn', '  bronx_borugh','B-r-0-n-x','broxn   '),'Bronx')

In [216]:
bnb['neighbourhood group'].value_counts()

Manhattan        17329
Brooklyn         16084
Queens            4533
Bronx              873
Staten Island      299
Name: neighbourhood group, dtype: int64

In [217]:
hoods = pd.DataFrame(bnb['neighbourhood'].value_counts())

In [218]:
hoods = hoods.sort_values(by=['neighbourhood'])

In [219]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['neighbourhood']) == str:
        bnb.at[ind,'neighbourhood'] = re.sub("-.*","",row['neighbourhood'])

39118it [00:01, 21553.78it/s]

In [220]:
chop = '\s*Brooklyn\s*$|\s*broxn\s*$|\s*Manhattan\s*$|\s*Queens\s*$|\s*,\s*$|\s*Bronx\s*$|\s*Staten Island\s*$|\s*Borough\s*$|\s*, Staten Island\s*$'

for ind, row in tqdm(bnb.iterrows()):
    if type(row['neighbourhood']) == str:
        bnb.at[ind,'neighbourhood'] = re.sub(chop,"",row['neighbourhood'])
        
for ind, row in tqdm(bnb.iterrows()):
    if type(row['neighbourhood']) == str:
        bnb.at[ind,'neighbourhood'] = re.sub(chop,"",row['neighbourhood'])

39118it [00:01, 19921.53it/s]
39118it [00:01, 20218.53it/s]

In [221]:
hoods.head(n=60)

                                                    neighbourhood
MidwoodBrooklyn-Brooklyn                                        1
KensingtonBrooklyn - **Borough**-Brooklyn - **B...              1
West Farms                                                      1
LongwoodBronx-Bronx                                             1
Rossville                                                       1
FlushingQueens-Queens                                           1
Theater DistrictManhattan-Manhattan                             1
GowanusBrooklyn-Brooklyn                                        1
RosedaleQueens-Queens                                           1
Bay Terrace, Staten Island                                      1
Springfield GardensQueens-Queens                                1
Borough ParkBrooklyn-Brooklyn                                   1
Bedford-Stuyvesantbrklyn-brklyn                                 1
Downtown BrooklynBrooklyn-Brooklyn                              1
Fort GreeneBrooklyn - **Borough**-Brooklyn - **...              1
East New YorkBrooklyn-Brooklyn                                  1
South SlopeBrooklyn-Brooklyn                                    1
Ditmars SteinwayQueens-Queens                                   1
BriarwoodQueens-Queens                                          1
Far RockawayQueens-Queens                                       1
Willowbrook                                                     1
Bedford-StuyvesantBrooklyn Borough-Brooklyn Bor...              1
Kingsbridgebroxn   -broxn                                       1
Stuyvesant TownManhattan-Manhattan                              1
New Dorp                                                        1
LaureltonQueens-Queens                                          1
Co-op City                                                      1
AllertonBronx-Bronx                                             1
Carroll GardensBrooklyn-Brooklyn                                1
St. GeorgeStaten Island-Staten Island                           1
St. AlbansQueens-Queens                                         1
HolliswoodQueens-Queens                                         1
HighbridgeBronx-Bronx                                           1
Fort Wadsworth                                                  1
BushwickBrooklyn - **Borough**-Brooklyn - **Bor...              1
Roosevelt IslandManhattan-Manhattan                             1
Emerson Hill                                                    1
StapletonStaten Island-Staten Island                            1
Mott HavenBronx-Bronx                                           1
Brooklyn HeightsBrooklyn-Brooklyn                               1
KingsbridgeBronx-Bronx                                          1
Lighthouse Hill                                                 1
Neponsit                                                        1
Silver Lake                                                     1
WilliamsburgBrooklyn - **Borough**-Brooklyn - *...              1
Civic CenterManhattan-Manhattan                                 1
KensingtonBrooklyn-Brooklyn                                     1
Cobble HillBrooklyn Borough-Brooklyn Borough                    1
ElmhurstQueens-Queens                                           1
Richmondtown                                                    1
Bedford-StuyvesantBrooklyn - **Borough**-Brookl...              2
Windsor TerraceBrooklyn-Brooklyn                                2
Park SlopeBrooklyn-Brooklyn                                     2
Westerleigh                                                     2
FlatbushBrooklyn-Brooklyn                                       2
Little ItalyManhattan-Manhattan                                 2
East ElmhurstQueens-Queens                                      2
Prospect-Lefferts GardensBrooklyn-Brooklyn                      2
Jackson HeightsQueens-Queens                                    2
Ozone ParkQueens-Queens                                         2

In [222]:
bnb['neighbourhood'] = bnb['neighbourhood'].replace('Co','Co-op City')

In [223]:
bnb.dtypes

0
id                            int64
name                         object
host id                       int64
host name                    object
neighbourhood group          object
neighbourhood                object
latitude                     object
longitude                    object
room and type                object
minimum nights               object
number of reviews (total)    object
last review (date)           object
reviews per month            object
floor                        object
noise.dB.                    object
price                        object
dtype: object

In [224]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['latitude']) == str:
        bnb.at[ind,'latitude'] = re.sub('[^\d\.]','', row['latitude'])

39118it [00:01, 21713.07it/s]

In [225]:
bnb['latitude']

1        40.64749
2        40.75362
3        40.80902
4        40.68514
5        40.79851
           ...
39114    40.67853
39115    40.70184
39116    40.81475
39117    40.75751
39118    40.76404
Name: latitude, Length: 39118, dtype: object

In [226]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['longitude']) == str:
        bnb.at[ind,'longitude'] = re.sub('[^\d\.]','', row['longitude'])

39118it [00:01, 21871.29it/s]

In [227]:
bnb['latitude']=bnb['latitude'].astype('float')
bnb['longitude']=bnb['longitude'].astype('float')

In [228]:
bnb

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,90

In [229]:
bnb['room and type'].value_counts()

Entire home/apt      20276
Private room         17553
Shared room            930
Room Type Private      300
Privatè-Room            59
Name: room and type, dtype: int64

In [230]:
bnb['room and type']= bnb['room and type'].replace(('Room Type Private', 'Privatè-Room'), 'Private room')

In [231]:
bnb['minimum nights'].value_counts()

1             10120
2              9300
3              6374
30             2920
4              2592
5              2399
7              1647
6               602
14              451
10              390
29              262
15              227
20              177
31              163
28              162
21              111
8               105
60               83
90               81
1 nights         79
2 nights         77
12               74
25               71
9                65
3 nights         55
13               41
180              38
45               29
4 nights         24
11               24
30 nights        24
365              22
120              21
18               20
16               15
100              13
17               13
26               13
5 nights         13
27               12
40               12
24               11
50               10
35               10
19                8
7 nights          8
14 nights         7
80                7
23                7
22                6
59                6
32                6
150               6
300               5
500               5
6 nights          5
70                5
55                4
75                4
200               4
360               4
62                2
999               2
93                2
29 nights         2
99                2
91                2
33                2
210               2
44                2
160               2
270               2
110               2
240               2
115               2
153               1
133               1
31 nights         1
354               1
265               1
37                1
225               1
20 nights         1
184               1
65                1
175               1
134               1
222               1
58                1
53                1
56                1
182               1
105               1
85                1
98                1
21 nights         1
39                1
299               1
364               1
74                1
198               1
122               1
43                1
250               1
480               1
10 nights         1
88                1
15 nights         1
186               1
366               1
68                1
1000              1
365 nights        1
87                1
1250              1
36                1
Name: minimum nights, dtype: int64

In [232]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['minimum nights']) == str:
        bnb.at[ind,'minimum nights'] = re.sub('\D','', row['minimum nights'])

39118it [00:01, 21508.46it/s]

In [233]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['number of reviews (total)']) == str:
        bnb.at[ind,'number of reviews (total)'] = re.sub('\D','', row['number of reviews (total)'])

39118it [00:01, 21856.75it/s]

In [234]:
bnb['number of reviews (total)'].value_counts()

0      7978
1      4181
2      2779
3      2017
4      1569
5      1301
6      1112
7       945
8       889
9       762
10      648
11      629
12      541
13      506
14      456
15      432
16      383
17      366
18      323
19      323
20      314
22      281
21      276
23      260
24      251
25      246
26      237
27      204
28      203
29      193
32      190
30      179
31      177
33      175
38      167
42      156
34      155
36      148
35      146
37      140
39      139
43      131
45      128
41      127
48      117
40      113
51      110
52      110
47      110
49      109
59      107
44      101
54       99
57       93
50       90
46       90
55       89
58       89
68       85
67       84
61       81
53       81
62       81
56       75
64       74
70       74
63       73
66       71
60       71
77       70
76       69
69       69
72       67
73       65
86       63
75       62
74       62
65       60
71       58
81       58
78       56
95       56
85       56
92       54
80       52
91       51
88       51
87       51
93       50
79       50
82       47
89       45
107      45
102      45
104      42
90       42
108      42
83       42
100      41
94       40
98       38
84       38
106      38
97       38
105      36
115      35
116      33
117      33
96       32
103      32
119      31
125      31
122      31
123      30
142      30
109      29
136      29
120      29
132      28
111      28
101      28
148      27
131      27
114      27
134      26
130      26
118      26
124      26
113      26
112      25
137      24
129      24
146      24
99       24
141      24
150      23
128      23
138      23
147      22
126      22
152      21
127      21
133      21
143      20
135      20
151      20
121      20
154      19
110      19
166      18
145      17
153      17
163      17
168      17
162      17
177      17
186      16
139      16
179      15
205      14
158      14
176      13
171      13
157      13
149      13
140      13
209      13
160      13
203      12
156      12
144      12
185      12
190      11
222      11
161      11
167      11
204      11
169      11
220      11
172      11
155      11
213      10
206      10
207      10
200      10
182      10
214      10
198      10
188      10
202      10
199       9
229       9
201       9
225       9
183       8
164       8
178       8
208       8
197       8
175       8
180       8
165       8
191       8
211       8
173       8
174       8
210       8
194       8
170       8
159       8
181       8
195       8
193       8
187       7
221       7
216       7
219       7
233       7
232       7
227       6
238       6
192       6
189       6
248       6
231       5
255       5
184       5
260       5
240       5
257       5
270       5
245       5
259       4
262       4
226       4
224       4
241       4
196       4
254       4
319       4
228       4
218       4
242       4
273       4
234       4
296       4
235       4
271       4
212       3
266       3
251       3
287       3
272       3
291       3
252       3
323       3
284       3
215       3
279       3
297       3
320       3
295       3
247       3
289       3
244       3
236       3
280       3
269       3
243       3
292       2
414       2
426       2
375       2
324       2
315       2
275       2
256       2
281       2
334       2
356       2
360       2
285       2
267       2
230       2
249       2
336       2
223       2
246       2
261       2
258       2
333       2
305       2
250       2
276       2
239       2
321       2
265       2
268       2
294       2
358       2
327       2
401       2
338       2
347       2
372       1
282       1
466       1
299       1
430       1
307       1
277       1
394       1
351       1
318       1
396       1
576       1
448       1
424       1
341       1
310       1
436       1
368       1
325       1
306       1
510       1
434       1
411       1
350       1
378       1
459       1
253       1
629       1
264       1
543       1
309       1
488       1
340       1
217       1
349       1
335       1
607       1
597       1
594       1
313       1
403       1
540       1
480       1
330       1
326       1
404       1
278       1
328       1
474       1
439       1
395       1
308       1
458       1
467       1
365       1
288       1
298       1
263       1
441       1
314       1
353       1
237       1
398       1
322       1
386       1
451       1
274       1
354       1
374       1
302       1
Name: number of reviews (total), dtype: int64

In [235]:
bnb['number of reviews (total)']=bnb['number of reviews (total)'].astype('int')

In [236]:
reviews = pd.DataFrame(bnb['last review (date)'].value_counts())

In [237]:

reviews = reviews.sort_values(by=['last review (date)'])

In [238]:
bnb['reviews per month'] = bnb['reviews per month'].astype('float')

In [239]:
bnb['reviews per month'].describe()

count    31140.000000
mean         1.375070
std          1.681448
min          0.010000
25%          0.190000
50%          0.720000
75%          2.030000
max         58.500000
Name: reviews per month, dtype: float64

In [240]:
bnb['floor']=bnb['floor'].replace(('First Floor', '1st-floor','1','0',0),1)
bnb['floor']=bnb['floor'].replace(('Second Floor', '2'),2)
bnb['floor']=bnb['floor'].replace(('Fifth Floor', '5th Floor', '5'),5)
bnb['floor']=bnb['floor'].replace(('Third Floor'),3)
bnb['floor']=bnb['floor'].replace(('Fourth Floor'),4)
bnb['floor']=bnb['floor'].replace(('Sixth Floor'),6)
bnb['floor']=bnb['floor'].replace(('Eighth Floor', '8'),8)
bnb['floor']=bnb['floor'].replace(('Seventh Floor'),7)
bnb['floor']=bnb['floor'].replace(('Tenth Floor'),10)
bnb['floor']=bnb['floor'].replace(('Thirteenth Floor'),13)
bnb['floor']=bnb['floor'].replace(('Eleventh Floor'),11)
bnb['floor']=bnb['floor'].replace(('Lower Level'),1)
bnb['floor']=bnb['floor'].replace(('Ninth Floor'),9)
bnb['floor']=bnb['floor'].replace(('Hundreth Floor'),100)
bnb['floor']=bnb['floor'].replace(('Sixteenth Floor'),16)
bnb['floor']=bnb['floor'].replace(('Seventeenth Floor'),17)
bnb['floor']=bnb['floor'].replace(('Twentieth Floor'),20)

In [241]:
bnb['floor']= bnb['floor'].astype('int')

In [242]:
bnb['floor'].describe()

count    39118.000000
mean         1.584744
std          1.501800
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        100.000000
Name: floor, dtype: float64

In [243]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['noise.dB.']) == str:
        bnb.at[ind,'noise.dB.'] = re.sub('[^\d\.]','', row['noise.dB.'])

39118it [00:01, 21016.36it/s]

In [244]:
bnb['noise.dB.']= bnb['noise.dB.'].astype('float')

In [245]:
bnb['noise.dB.'].describe()

count    39118.000000
mean        62.700358
std          6.515328
min         22.964360
25%         56.054278
50%         62.478632
75%         69.056465
max         98.056465
Name: noise.dB., dtype: float64

In [246]:
bnb

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,73.97237,Private room,1,9,2018-10-19,0.21,1,69.056465,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56.054278,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,NaN,1,56.054278,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69.056465,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,73.94399,Entire home/apt,10,9,2018-11-19,0.10,1,56.054278,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,NaN,1,69.056465,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,NaN,1,69.056465,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,NaN,1,56.054278,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,NaN,1,56.054278,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,NaN,1,56.054278,90

In [247]:
prices = pd.DataFrame(bnb['price'].value_counts()).sort_values(by=['price'])

In [248]:
prices.head(50)

                              price
393                               1
$479                              1
$50/- only                        1
$280open to negotiate             1
$900/- only                       1
920                               1
$295open to negotiate             1
930                               1
332                               1
$416                              1
$249approx                        1
$$65open to negotiate             1
$358                              1
$474                              1
331                               1
$549                              1
$40/- only                        1
$20open to negotiate              1
$276                              1
1978                              1
$1,494                            1
3512                              1
$180open to negotiate             1
$280approx                        1
418                               1
$192                              1
$503                              1
472                               1
503                               1
$227approx                        1
$220approx                        1
$$113approxopen to negotiate      1
428                               1
1099                              1
342                               1
539                               1
$426                              1
577                               1
311                               1
$$275approx                       1
$595                              1
$18                               1
$22/- only                        1
875                               1
$7,500                            1
447                               1
1799                              1
299/- only                        1
$1,750                            1
$100open to negotiate             1

In [249]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['price']) == str:
        bnb.at[ind,'price'] = re.sub('[^\d\.]','', row['price'])

39118it [00:01, 21251.63it/s]

In [250]:
bnb['price']=bnb['price'].astype('float')

In [251]:
bnb['price'].describe()

count    39118.000000
mean       152.427297
std        243.139941
min          0.000000
25%         69.000000
50%        105.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [252]:
bnb

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,73.97237,Private room,1,9,2018-10-19,0.21,1,69.056465,149.0
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56.054278,225.0
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,NaN,1,56.054278,150.0
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69.056465,89.0
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,73.94399,Entire home/apt,10,9,2018-11-19,0.10,1,56.054278,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,NaN,1,69.056465,70.0
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,NaN,1,69.056465,40.0
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,NaN,1,56.054278,115.0
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,NaN,1,56.054278,55.0
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,NaN,1,56.054278,90.0

In [253]:
bnb.dtypes

0
id                             int64
name                          object
host id                        int64
host name                     object
neighbourhood group           object
neighbourhood                 object
latitude                     float64
longitude                    float64
room and type                 object
minimum nights                object
number of reviews (total)      int64
last review (date)            object
reviews per month            float64
floor                          int64
noise.dB.                    float64
price                        float64
dtype: object

In [254]:
bnb.isna().sum()

0
id                              0
name                          416
host id                         0
host name                      16
neighbourhood group             0
neighbourhood                  30
latitude                        0
longitude                       0
room and type                   0
minimum nights                  0
number of reviews (total)       0
last review (date)           7978
reviews per month            7978
floor                           0
noise.dB.                       0
price                           0
dtype: int64

In [255]:
bnb['name'].fillna('None',inplace=True)

In [256]:
bnb[bnb['host name'].isna()]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
298,100184,Bienvenue,526653,NaN,Queens,Queens Village,40.72413,73.76133,Private room,1,43,2019-07-08,0.45,5,62.478632,50.0
2164,1449546,Cozy Studio in Flatbush,7779204,NaN,Brooklyn,Flatbush,40.64965,73.96154,Entire home/apt,30,49,2017-01-02,0.69,1,69.056465,100.0
4584,4183989,SPRING in the City!! Zen-Style Tranquil Bedroom,919218,NaN,Manhattan,Harlem,40.80606,73.95061,Private room,3,34,2019-05-23,1.00,1,56.054278,86.0
5252,4763327,"Luxurious, best location, spa inc'l",24576978,NaN,Brooklyn,Greenpoint,40.72035,73.95355,Entire home/apt,1,1,2015-10-20,0.02,1,69.056465,195.0
6517,6292866,Modern Quiet Gem Near All,32722063,NaN,Brooklyn,East Flatbush,40.65263,73.93215,Entire home/apt,2,182,2019-06-19,3.59,1,69.056465,85.0
6593,6360224,"Sunny, Private room in Bushwick",33134899,NaN,Brooklyn,Bushwick,40.70146,73.92792,Private room,1,1,2015-07-01,0.02,1,69.056465,37.0
7059,6786181,R&S Modern Spacious Hideaway,32722063,NaN,Brooklyn,East Flatbush,40.64345,73.93643,Entire home/apt,2,157,2019-06-19,3.18,1,69.056465,100.0
7842,7556587,Sunny Room in Harlem,39608626,NaN,Manhattan,Harlem,40.82929,73.94182,Private room,1,1,2015-08-01,0.02,1,56.054278,28.0
11307,10709846,"Sunny, spacious room in Greenpoint",7822683,NaN,Brooklyn,Greenpoint,40.73539,73.95838,Private room,10,2,2016-11-05,0.05,1,69.056465,55.0
11781,11553543,Cozy Room Astoria,26138712,NaN,Queens,Ditmars Steinway,40.77587,73.91775,Private room,1,5,2017-01-01,0.13,5,62.478632,45.0
12211,12113879,"Sunny, Large West Village 1 BR Near Everything",5300585,NaN,Manhattan,Chelsea,40.73949,73.99801,Entire home/apt,4,81,2019-07-02,2.11,1,56.054278,220.0
22228,21787094,Spacious and Bright Midtown East Apartment,415290,NaN,Manhattan,Upper East Side,40.76436,73.96836,Entire home/apt,1,0,NaN,NaN,1,56.054278,325.0
22448,21901156,Best Deal! Lovely place in Manhattan! Time Squ...,159156636,NaN,Manhattan,Hell's Kitchen,40.75656,73.99063,Private room,1,109,2019-01-01,5.97,1,56.054278,120.0
22648,21990808,***SLEEPING IN THE GOLDEN PLACE***,159156636,NaN,Manhattan,Hell's Kitchen,40.75835,73.99065,Private room,1,88,2018-12-14,4.93,1,56.054278,120.0
24519,23660605,Private Bedroom w/ Balcony view of Central Park,177146433,NaN,Manhattan,East Harlem,40.79766,73.94824,Private room,1,6,2018-08-12,0.46,1,56.054278,139.0
31259,30468335,LARGE Prospect Lefferts Gardens Bedroom,228750026,NaN,Brooklyn,Flatbush,40.65152,73.95271,Private room,7,0,NaN,NaN,1,69.056465,55.0

In [257]:
bnb[bnb['host name'].isna()]['host id'].value_counts()

32722063     2
159156636    2
526653       1
7779204      1
919218       1
24576978     1
33134899     1
39608626     1
7822683      1
26138712     1
5300585      1
415290       1
177146433    1
228750026    1
Name: host id, dtype: int64

In [258]:
bnb[bnb['host id']==32722063]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
6517,6292866,Modern Quiet Gem Near All,32722063,NaN,Brooklyn,East Flatbush,40.65263,73.93215,Entire home/apt,2,182,2019-06-19,3.59,1,69.056465,85.0
7059,6786181,R&S Modern Spacious Hideaway,32722063,NaN,Brooklyn,East Flatbush,40.64345,73.93643,Entire home/apt,2,157,2019-06-19,3.18,1,69.056465,100.0

In [259]:
bnb[bnb['host id']==159156636]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
22448,21901156,Best Deal! Lovely place in Manhattan! Time Squ...,159156636,NaN,Manhattan,Hell's Kitchen,40.75656,73.99063,Private room,1,109,2019-01-01,5.97,1,56.054278,120.0
22648,21990808,***SLEEPING IN THE GOLDEN PLACE***,159156636,NaN,Manhattan,Hell's Kitchen,40.75835,73.99065,Private room,1,88,2018-12-14,4.93,1,56.054278,120.0

In [260]:
bnb['host name'].fillna('None',inplace=True)

In [261]:
bnb.isna().sum()

0
id                              0
name                            0
host id                         0
host name                       0
neighbourhood group             0
neighbourhood                  30
latitude                        0
longitude                       0
room and type                   0
minimum nights                  0
number of reviews (total)       0
last review (date)           7978
reviews per month            7978
floor                           0
noise.dB.                       0
price                           0
dtype: int64

In [262]:
bnb[bnb['neighbourhood'].isna()]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
4141,3741405,2br in Manhattan NY,10577253,Nataly,Manhattan,NaN,40.81217,73.95303,Entire home/apt,1,3,2016-01-02,0.05,1,56.054278,150.0
6115,5783517,Cozy & Clean #1,23533897,Fatou,Brooklyn,NaN,40.67383,73.95137,Private room,2,61,2019-06-26,1.17,1,69.056465,50.0
8691,8368708,Cozy 1 bedroom apt Prime Location!!,20413250,Sara,Queens,NaN,40.76307,73.92247,Entire home/apt,14,0,NaN,NaN,5,62.478632,150.0
11351,10798553,Gorgeous Greenpoint: Sublet April 10th - 27th,798949,Rachel,Brooklyn,NaN,40.72540,73.95246,Entire home/apt,10,0,NaN,NaN,1,69.056465,99.0
12316,12266323,"The Heart Of NYC, 3min Walk To Grand Central",5004109,Michelle,Manhattan,NaN,40.75001,73.97739,Entire home/apt,1,45,2019-06-30,1.16,1,56.054278,225.0
12956,13017140,Bright & Cozy 1BR + Home Gym!,65727695,Shutong,Manhattan,NaN,40.81632,73.96007,Entire home/apt,2,2,2017-01-02,0.06,1,56.054278,120.0
14729,14386892,"Private Comfy 2 Room Apt, 23min to Manhattan",88361314,Cindy,Brooklyn,NaN,40.65823,73.98059,Entire home/apt,4,75,2019-06-10,2.16,1,69.056465,99.0
15828,15790820,Beautiful Room in Clinton Hill,33924547,Laura,Brooklyn,NaN,40.68978,73.95339,Private room,3,0,NaN,NaN,1,69.056465,130.0
16159,16122024,B & B in NYC!!,66915031,Sharon,Manhattan,NaN,40.84657,73.93570,Private room,2,55,2019-06-11,5.54,1,56.054278,65.0
17036,16854141,"Snug, Cozy 1 bedroom Apartment",18595156,Dwane,Brooklyn,NaN,40.65877,73.89631,Entire home/apt,1,68,2019-06-08,2.27,1,69.056465,100.0
19450,19532789,NEWLY Renovated Private 2 Bed Apt on 1 st Floor..,15192,Oscar,Brooklyn,NaN,40.68268,73.94548,Entire home/apt,4,33,2019-06-22,1.40,1,69.056465,95.0
21225,21098848,Sunny 1 bedroom suite in midtown Manhattan,120762452,Stanley,Manhattan,NaN,40.74877,73.97565,Entire home/apt,30,1,2019-02-01,0.19,1,56.054278,175.0
22010,21659494,"Spacious queen bedroom, private bath in Brooklyn",26379887,Marine,Brooklyn,NaN,40.72891,73.95618,Private room,2,4,2018-10-31,0.20,1,69.056465,150.0
22790,22078785,AMAZING private room in 2bed lower east side apt,3562795,Rachel,Manhattan,NaN,40.71441,73.98655,Private room,4,0,NaN,NaN,1,56.054278,100.0
26215,25763994,Cozy Hamilton Heights Room for 1 or 2,33680599,Kaila,Manhattan,NaN,40.82913,73.94718,Private room,2,17,2019-06-15,1.35,1,56.054278,55.0
27193,26858196,AWESOME 2 BEDS - QUEEN + SOFA - NEXT TO METRO,23188519,Emily Wes,Brooklyn,NaN,40.69561,73.94972,Private room,30,22,2019-06-22,1.83,1,69.056465,75.0
27706,27388568,Casa Finca Sanctuary Duplex w/ Private Garden,895135,Suanny,Brooklyn,NaN,40.70732,73.94536,Private room,3,12,2019-07-02,1.08,1,69.056465,130.0
28386,28052259,Manhattan Townhouse,76350146,David,Manhattan,NaN,40.74123,73.97559,Private room,2,17,2019-07-01,1.95,1,56.054278,150.0
28596,28291704,Mott Haven Dorm-Bed A,174785358,Rem,Bronx,NaN,40.81020,73.93147,Shared room,1,18,2019-06-20,1.93,5,78.474074,28.0
31014,30378844,Mellow Stuyvesant Bedroom Madison 2L-2,226410657,Nina,Brooklyn,NaN,40.68768,73.93076,Private room,30,2,2019-06-01,0.86,1,69.056465,42.0
31309,30506672,Peaceful Haven in NYC!,24419496,Melissa,Manhattan,NaN,40.77604,73.94524,Entire home/apt,3,1,2019-01-03,0.16,1,56.054278,125.0
31491,30656450,West Village Dream Townhouse,912324,Rae,Manhattan,NaN,40.73704,74.00501,Entire home/apt,3,5,2019-06-21,0.80,1,57.054278,500.0
32988,32036850,Charming lower east side room,165863135,Amanda,Manhattan,NaN,40.72026,73.98787,Private room,20,2,2019-04-19,0.48,1,56.054278,80.0
34227,33169890,Cozy Bedroom on Upper west near Columbia U,233917490,Yoannie,Manhattan,NaN,40.80221,73.96677,Private room,1,0,NaN,NaN,1,56.054278,40.0
34714,33592086,Huge Room For Rent Close to JFK and the Q train,197368927,Cebile,Brooklyn,NaN,40.60898,73.95341,Private room,1,5,2019-07-06,1.83,1,69.056465,65.0
34897,33719823,"Large, Bright, Luxury Chelsea Studio/ Best Are...",254189342,Kimberley,Manhattan,NaN,40.75104,73.99544,Entire home/apt,4,1,2019-07-07,1.00,1,56.054278,200.0
36268,34652761,Entire 1 Bedroom Apartment with Rooftop Access,37426897,Rosie,Brooklyn,NaN,40.69474,73.96655,Entire home/apt,1,6,2019-06-24,4.19,1,69.056465,100.0
37124,35220992,"Lovely Fam hse, one lg quest private BR on 2n...",161906388,Imelda,Queens,NaN,40.68794,73.85566,Private room,1,4,2019-06-30,4.00,5,62.478632,45.0
38091,35804885,Cozy Classic Convenient Apartment Near The Park,269345151,Marlene,Brooklyn,NaN,40.67221,73.94847,Entire home/apt,2,0,NaN,NaN,1,69.056465,100.0
38311,35945192,Very cozy private bedroom The heart of Astoria,270374596,Loubna,Queens,NaN,40.76591,73.90934,Private room,3,0,NaN,NaN,5,62.478632,90.0

In [263]:
bnb['neighbourhood'].fillna('None',inplace=True)

In [264]:
bnb.isna().sum()

0
id                              0
name                            0
host id                         0
host name                       0
neighbourhood group             0
neighbourhood                   0
latitude                        0
longitude                       0
room and type                   0
minimum nights                  0
number of reviews (total)       0
last review (date)           7978
reviews per month            7978
floor                           0
noise.dB.                       0
price                           0
dtype: int64

In [265]:
bnb[bnb['reviews per month'].isna() & bnb['number of reviews (total)']==0]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,73.97237,Private room,1,9,2018-10-19,0.21,1,69.056465,149.0
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56.054278,225.0
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,NaN,1,56.054278,150.0
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69.056465,89.0
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,73.94399,Entire home/apt,10,9,2018-11-19,0.10,1,56.054278,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,NaN,1,69.056465,70.0
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,NaN,1,69.056465,40.0
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,NaN,1,56.054278,115.0
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,NaN,1,56.054278,55.0
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,NaN,1,56.054278,90.0

In [266]:
bnb[bnb['number of reviews (total)']==0]

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,NaN,1,56.054278,150.0
17,7750,Huge 2 BR Upper East Cental Park,17985,Sing,Manhattan,East Harlem,40.79685,73.94872,Entire home/apt,7,0,NaN,NaN,1,56.054278,190.0
22,8700,Magnifique Suite au N de Manhattan - vue Cloitres,26394,Claude & Sophie,Manhattan,Inwood,40.86754,73.92639,Private room,4,0,NaN,NaN,1,56.054278,80.0
28,11452,Clean and Quiet in Brooklyn,7355,Vt,Brooklyn,Bedford,40.68876,73.94312,Private room,60,0,NaN,NaN,1,69.056465,35.0
30,11943,Country space in the city,45445,Harriet,Brooklyn,Flatbush,40.63702,73.96327,Private room,1,0,NaN,NaN,1,69.056465,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,NaN,1,69.056465,70.0
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,NaN,1,69.056465,40.0
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,NaN,1,56.054278,115.0
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,NaN,1,56.054278,55.0
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,NaN,1,56.054278,90.0

In [267]:
bnb['reviews per month'].fillna(0,inplace=True)

In [268]:
bnb.isna().sum()

0
id                              0
name                            0
host id                         0
host name                       0
neighbourhood group             0
neighbourhood                   0
latitude                        0
longitude                       0
room and type                   0
minimum nights                  0
number of reviews (total)       0
last review (date)           7978
reviews per month               0
floor                           0
noise.dB.                       0
price                           0
dtype: int64

In [269]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['last review (date)']) == str:
        if re.search(r'[^\d\d\d\d\-\d\d\-\d\d]', row['last review (date)']) != None:
            print('match')

39118it [00:01, 28175.04it/s]

In [270]:
date_string = "2016-01-02"

# format date
date_object = datetime.strptime(date_string, "%Y-%m-%d")

print("date_object: ", date_object)

date_object:  2016-01-02 00:00:00

In [271]:
for ind, row in tqdm(bnb.iterrows()):
    if type(row['last review (date)']) == str:
        bnb.at[ind,'last review (date)'] = datetime.strptime(row['last review (date)'], "%Y-%m-%d")

39118it [00:01, 19772.43it/s]

In [272]:
bnb.dtypes

0
id                             int64
name                          object
host id                        int64
host name                     object
neighbourhood group           object
neighbourhood                 object
latitude                     float64
longitude                    float64
room and type                 object
minimum nights                object
number of reviews (total)      int64
last review (date)            object
reviews per month            float64
floor                          int64
noise.dB.                    float64
price                        float64
dtype: object

In [273]:
bnb

,id,name,host id,host name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,73.97237,Private room,1,9,2018-10-19 00:00:00,0.21,1,69.056465,149.0
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,73.98377,Entire home/apt,1,45,2019-05-21 00:00:00,0.38,1,56.054278,225.0
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,73.94190,Private room,3,0,NaN,0.00,1,56.054278,150.0
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,73.95976,Entire home/apt,1,270,2019-07-05 00:00:00,4.64,1,69.056465,89.0
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,73.94399,Entire home/apt,10,9,2018-11-19 00:00:00,0.10,1,56.054278,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford,40.67853,73.94995,Private room,2,0,NaN,0.00,1,69.056465,70.0
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,73.93317,Private room,4,0,NaN,0.00,1,69.056465,40.0
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,73.94867,Entire home/apt,10,0,NaN,0.00,1,56.054278,115.0
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,73.99112,Shared room,1,0,NaN,0.00,1,56.054278,55.0
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,73.98933,Private room,7,0,NaN,0.00,1,56.054278,90.0

In [274]:
# Leaving last review (date) as NaN for all NaN's because no last review date is possible for an airbnb with no reviews
# will handle this on a case by case basis in future steps

In [275]:
bnb.to_csv('data/bnbClean.csv')

In [276]:
bnb.isna().sum()

0
id                              0
name                            0
host id                         0
host name                       0
neighbourhood group             0
neighbourhood                   0
latitude                        0
longitude                       0
room and type                   0
minimum nights                  0
number of reviews (total)       0
last review (date)           7978
reviews per month               0
floor                           0
noise.dB.                       0
price                           0
dtype: int64

In [277]:
hoods = bnb['neighbourhood'].value_counts()

In [278]:
hoods

Williamsburg           3145
Bedford                2983
Harlem                 2138
Bushwick               1980
Hell's Kitchen         1575
Upper West Side        1538
East Village           1506
Upper East Side        1434
Crown Heights          1251
Midtown                1225
East Harlem             913
Chelsea                 883
Greenpoint              870
Lower East Side         735
Washington Heights      717
Astoria                 716
West Village            598
Financial District      594
Flatbush                500
Clinton Hill            474
Prospect                432
Long Island City        429
Park Slope              420
East Flatbush           402
Murray Hill             393
Fort Greene             377
Kips Bay                370
Ridgewood               338
Flushing                320
Greenwich Village       310
Chinatown               294
Gramercy                291
SoHo                    290
Sunnyside               290
Prospect Heights        289
Sunset Park             288
Morningside Heights     272
Ditmars Steinway        245
South Slope             229
Theater District        228
Inwood                  204
Gowanus                 194
Elmhurst                192
Nolita                  187
Jamaica                 185
Carroll Gardens         184
Woodside                175
East New York           165
Jackson Heights         157
East Elmhurst           153
Kensington              147
Boerum Hill             147
Tribeca                 140
Brooklyn Heights        126
Sheepshead Bay          123
Windsor Terrace         119
Forest Hills            115
Bay Ridge               114
Canarsie                114
Borough Park            105
Cypress Hills           103
Maspeth                  95
Little Italy             95
Rego Park                90
Midwood                  90
Cobble Hill              77
Woodhaven                71
Richmond Hill            71
Arverne                  68
Springfield Gardens      68
Roosevelt Island         68
Red Hook                 65
Brighton Beach           63
Flatlands                63
Flatiron District        63
Bensonhurst              61
Downtown                 61
NoHo                     60
St. Albans               59
Two Bridges              57
Kingsbridge              57
Gravesend                55
Battery Park City        54
Brownsville              53
Ozone Park               53
Queens Village           52
Longwood                 52
Briarwood                50
Fordham                  49
Rosedale                 48
Corona                   47
Rockaway Beach           47
Glendale                 43
Port Morris              41
Mott Haven               41
St. George               40
Civic Center             40
Fort Hamilton            40
Wakefield                39
Concourse                39
Tompkinsville            36
South Ozone Park         36
Stuyvesant Town          34
Columbia St              34
Williamsbridge           33
Allerton                 33
Bayside                  31
None                     30
Parkchester              28
Concourse Village        28
Norwood                  27
Vinegar Hill             27
DUMBO                    26
Kew Gardens              25
Far Rockaway             25
Pelham Gardens           25
Fresh Meadows            24
Cambria Heights          23
Highbridge               23
Kew Gardens Hills        22
Throgs Neck              21
Stapleton                21
Belmont                  21
Concord                  20
Middle Village           20
Claremont Village        19
University Heights       19
Clason Point             18
Randall Manor            17
Howard Beach             16
College Point            16
Bath Beach               16
Mount Hope               15
West Brighton            15
Arrochar                 15
Hunts Point              14
Jamaica Estates          14
Morris Heights           14
City Island              14
Coney Island             13
Bronxdale                13
Clifton                  13
Soundview                13
Pelham Bay               13
Morrisania               12
Navy Yard                12
Bellerose                12
Bayswater                12
Laurelton                12
Eastchester              12
Whitestone               11
Dyker Heights            10
Fieldston                10
Schuylerville            10
Marble Hill              10
Morris Park              10
Hollis                   10
East Morrisania           9
Edgemere                  9
Melrose                   9
Westchester Square        9
Great Kills               9
Manhattan Beach           8
Castle Hill               8
Van Nest                  8
Riverdale                 8
Edenwald                  8
Douglaston                8
Woodlawn                  8
Tremont                   8
New Springville           7
North Riverdale           7
Jamaica Hills             7
Sea Gate                  7
Mariners Harbor           7
Baychester                7
Rosebank                  6
Belle Harbor              6
Bergen Beach              6
Unionport                 6
Port Richmond             6
Bay Terrace               6
Midland Beach             6
Dongan Hills              6
South Beach               5
Grant City                5
Grymes Hill               5
Mount Eden                5
New Dorp Beach            5
Shore Acres               5
Arden Heights             4
Tottenville               4
Castleton Corners         4
Oakwood                   4
Spuyten Duyvil            4
Bull's Head               4
Todt Hill                 3
Holliswood                3
Olinville                 3
New Brighton              3
Mill Basin                3
Eltingville               3
Graniteville              3
Little Neck               3
Prince's Bay              3
Huguenot                  2
Breezy Point              2
Westerleigh               2
Howland Hook              2
Co-op City                1
Willowbrook               1
West Farms                1
Rossville                 1
Richmondtown              1
New Dorp                  1
Fort Wadsworth            1
Lighthouse Hill           1
Neponsit                  1
Silver Lake               1
Emerson Hill              1
Name: neighbourhood, dtype: int64